"""empty message

Revision ID: 37d94f9cfbcc
Revises: 
Create Date: 2020-01-30 09:32:21.619333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37d94f9cfbcc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ngc', sa.String(length=100), nullable=False),
    sa.Column('object_type', sa.String(length=100), nullable=False),
    sa.Column('season', sa.String(length=100), nullable=False),
    sa.Column('magnitude', sa.String(length=100), nullable=False),
    sa.Column('constellation_eng', sa.String(length=100), nullable=False),
    sa.Column('constellation_fr', sa.String(length=100), nullable=False),
    sa.Column('constellation_lat', sa.String(length=100), nullable=False),
    sa.Column('right_ascension', sa.String(length=100), nullable=False),
    sa.Column('declinaison', sa.String(length=100), nullable=False),
    sa.Column('distance', sa.String(length=100), nullable=False),
    sa.Column('size', sa.String(length=100), nullable=False),
    sa.Column('discoverer', sa.String(length=100), nullable=False),
    sa.Column('year', sa.String(length=100), nullable=False),
    sa.Column('image_URL', sa.String(length=500), nullable=False),
    sa.Column('constellation', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('constellation'),
    sa.UniqueConstraint('constellation_eng'),
    sa.UniqueConstraint('constellation_fr'),
    sa.UniqueConstraint('constellation_lat'),
    sa.UniqueConstraint('declinaison'),
    sa.UniqueConstraint('discoverer'),
    sa.UniqueConstraint('distance'),
    sa.UniqueConstraint('image_URL'),
    sa.UniqueConstraint('magnitude'),
    sa.UniqueConstraint('ngc'),
    sa.UniqueConstraint('object_type'),
    sa.UniqueConstraint('right_ascension'),
    sa.UniqueConstraint('season'),
    sa.UniqueConstraint('size'),
    sa.UniqueConstraint('year')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messier')
    # ### end Alembic commands ###
